- name: insgall and run nginx
  hosts: web
  become: yes # means root user
  task: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started