- name: variable
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with aws"
    DURATION: "120"
    PLATFORM: "JoinDevops"
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "I learn {{ COURSE }}, course duration {{ DURATION }}hrs, platform is {{ PLATFORM }}"