- name: variable
  hosts: local
  connection: local
  vars: # play leval variables
    COURSE: "Devops with aws"
    DURATION: "120"
    PLATFORM: Join Devops
  tasks:
  - name: print the variable
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "I learn {{ COURSE }}, course duration {{ DURATION }}hrs, platform is {{ PLATFORM }}"