- name: variables from files
  hosts: local
  connection: local
  var_files:
    course.yaml
  task:
  - name: print course information
    ansible.builtin.debug:
      msg: "I learn {{ COURSE }}, course duration {{ DURATION }}hrs, platform is {{ PLATFORM }}"