- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: please enter course name
      private: false # it is not confidential information
    - name: DURATION
      prompt: please enter course duration
      private: false
    - name: PLATFORM
      prompt: please enter platform name
      private: false
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "I learn {{ COURSE }}, course duration {{ DURATION }}hrs, platform is {{ PLATFORM }}"