- name: variables form args
  hosts: local
  connection: local
  tasks:
  - name: print the variables from arguments
    ansible.builtin.debug:
      msg: "I learn {{ COURSE }}, course duration {{ DURATION }}hrs, platform is {{ PLATFORM }}"