- name: variables prefrences
  hosts: local
  connection: local
  vars:
    GREET: PLAY
  # vars_files:
  #   course.yaml
  vars_prompt:
    - name: GREET
      prompt: please enter Greet Name
      private: false
  tasks:
  - name: print the variable from task level
    # vars:
    #   GREET: TASK
    ansible.builtin.debug:
      msg: "Hell From {{ GREET }}"



# 1. command lines or args
# 2. From task level
# 3. From FILES Level