- name: check the value is greater than 10
  hosts: local
  connection: local
  vars:
    given_number: 10
  tasks:
  - name: print if the number is greter than 10
    ansible.builtin.debug:
      msg: "Given number {{ given_number}} is greater than 10"
    when: given_number > 10
  tasks:
  - name: print if the number is less than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ given_number}} is less than or equal to 10"
    when: given_number <= 10