- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install list of packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - gcc
    - mysql
    - git
    - zip

