- name: filters
  hosts: local
  connection: local
  tasks:
  - name: filters
    ansible.builtin.debug:
      msg: " Hello {{ person | default('Ramesh') }}"

  - name: converting string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: " Fruits are: {{ fruits | split(',') }}"

  - name: converting map into list
    vars:
      course:
        name: aws
        duration: 120
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }} "
    
  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'aws'}
      - {'key': 'duration', 'value': 120}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }} " 

  - name: convert upper to lower
    vars:
      name: "Gowtham Nagiri"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"


