- name: filters
  hosts: local
  connection: local
  tasks:
  - name: filters
    ansible.builtin.debug:
      msg: " Hello {{ person | default('Ramesh') }}"

  - name: converting string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: " Fruits are: {{ fruits | split(',') }}"

  - name: converting map into list
    vars:
      course:
        name: aws
        duration: 120
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }} "
