- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0b5c2033b2ab9ca24
    sg_id: sg-0a8f35b732cc9a366
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instancies:
    - mysql
    - backend
    - frontend
  tasks:
  - name: install python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instancies }}"
    register: ec2_info

  - name: print the ec2-info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"

  - name: print private address
    ansible.builtin.debug:
      msg: "{{ item.item}}: {{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results}}"
